name: Install GDAL Windows

on:
  workflow_dispatch:
  push:
    branches:
      - ci
jobs:
  install-gdal:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download OSGeo4W installer script
        uses: actions/download-artifact@v3
        with:
          name: osgeo4w-installer-script
          path: ./osgeo4w_installer.bat

      - name: Run OSGeo4W installer
        run: |
          cmd.exe /c call ./osgeo4w_installer.bat ^
              --package-list=gdal ^
              --package-list=python3-gdal ^
              --package-list=proj ^
              --package-list=proj-data ^
              --resolve-dependencies=yes ^
              --auto-install=yes ^
              --auto-select=yes ^
              --quiet=yes

      - name: Set environment variables
        run: |
          setx GDAL_VERSION 3.7.2 /M
          setx GDAL_DRIVER_PATH "C:\OSGeo4W\apps\gdal\lib\gdalplugins" /M
          setx GDAL_DATA "C:\OSGeo4W\apps\gdal\share\gdal" /M
          setx PROJ_LIB "C:\OSGeo4W\share\proj" /M

      - name: Create symlink for Python bindings
        run: |
          mklink /D "C:\Program Files\Python39\Lib\site-packages\osgeo" "C:\OSGeo4W\apps\Python39\Lib\site-packages\osgeo"

      - name: Verify GDAL installation
        run: gdalinfo --version
