name: Build and Test Flows2FIM - Linux

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - ci

jobs:
  build:
    name: Build flows2fim
    
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Run Docker Compose
      run: |
        docker compose up -d
        docker ps

    - name: Attach to running container and Build
      run: |
        CONTAINER_ID=$(docker ps -q | head -n 1)
        if [ -n "$CONTAINER_ID" ]; then
          docker exec $CONTAINER_ID /bin/bash -c "./scripts/build-windows-amd64.sh"  
          docker compose down
        else
          echo "No running containers found"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim
        path: builds/windows-amd64
  
test:
    name: Test flows2fim
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: flows2fim-windows-amd64
        path: builds/windows-amd64
    
    - name: Add flows2fim to PATH
      run: |
        ls -R builds/windows-amd64
        sudo chmod a+x ./builds/windows-amd64/flows2fim 
        ./builds/windows-amd64/flows2fim --version
        echo "builds/windows-amd64" >> $GITHUB_PATH

    - name: Verify flows2fim is available
      run: |
        ./flows2fim --version

