name: Build and Test Flows2FIM

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - ci
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: ./scripts/build-linux-amd64.sh
  test: