name: Build Flows2FIM

on:
  workflow_dispatch:
  push:
    branches:
      - ci
  # release:
  #   types: [created, edited, published]

inputs:
  windows_buildpath: builds/windows-amd64
  linux_buildpath: builds/linux-amd64

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    # defaults:
    #   run:
    #     working-directory: ./scripts

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
      run: go version

    - name: Run Windows build script
      if: matrix.os == 'windows-latest'
      run: |
        echo "Building for Windows..."
        ./scripts/build-windows-amd64.sh

    - name: Create Windows artifact
      if: matrix.os == 'windows-latest'
      id: windows_artifact
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim-${{ matrix.os }}
        path: ${{ inputs.windows_buildpath }}
        
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim-${{ matrix.os }}
        path: ${{ inputs.windows_buildpath }}

    - name: Run Linux build script
      if: matrix.os == 'ubuntu-latest'
      run: |
         echo "Building for Linux..."
        ./scripts/build-linux-amd64.sh

    - name: Create Linux artifact
      id: linux_artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: ${{ inputs.linux_buildpath }}
      
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim-${{ matrix.os }}
        path: ${{ inputs.linux_buildpath }}

