name: Build Flows2FIM

on:
  workflow_dispatch:
  push:
    branches:
      - ci
  # release:
  #   types: [created, edited, published]

jobs:
  upload:
    name: Generate Build Artifacts

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_version: [linux-amd64, windows-amd64]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
      # run: go version

    - name: Build
      run: |
        mkdir artifacts/flows2fim
        ./scripts/build-${{ matrix.build_version }}.sh > artifacts/flows2fim
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim-${{ matrix.build_version }}
        path: artifacts/flows2fim

    # - name: Run Windows build script
    #   if: ${{ matrix.os }} == 'windows-latest'
    #   run: |
    #     echo "Building for Windows..."
    #     ./scripts/build-windows-amd64.sh

    # - name: Create Windows artifact
    #   if: ${{ matrix.os }} == 'windows-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: flows2fim-${{ matrix.os }}
    #     path: ${{ inputs.windows_buildpath }}
        
    # - name: Upload Windows artifacts
    #   if: ${{ matrix.os }} == 'windows-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: flows2fim-${{ matrix.os }}
    #     path: ${{ inputs.windows_buildpath }}

    # - name: Run Linux build script
    #   if: ${{ matrix.os }} == 'ubuntu-latest'
    #   run: |
    #      echo "Building for Linux..."
    #     ./scripts/build-linux-amd64.sh

    # - name: Create Linux artifact
    #   if: ${{ matrix.os }} == 'ubuntu-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: linux-artifact
    #     path: ${{ inputs.linux_buildpath }}
      
    # - name: Upload Linux artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: flows2fim-${{ matrix.os }}
    #     path: ${{ inputs.linux_buildpath }}

