name: Build Flows2FIM

on:
  workflow_dispatch:
  push:
    branches:
      - ci
  # release:
  #   types: [created, edited, published]

jobs:
  build:
    name: Build & Upload Artifacts

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_version: linux-amd64
          - os: windows-latest  
            build_version: windows-amd64
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build 
      run: |
        ./scripts/build-${{ matrix.build_version }}.sh
  
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: flows2fim-${{ matrix.build_version }}
        path: builds/${{ matrix.build_version }}

