name: Test Flows2FIM

on: 
  workflow_dispatch:
  push:
    branches:
      - ci
  # pull_request:

jobs:
  download:
    name: Download Artifact 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_version: linux-amd64
          # - os: windows-latest  
          #   build_version: windows-amd64

    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: flows2fim-${{ matrix.build_version }}
        path: builds/${{ matrix.build_version }}
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: 12918961000

    - name: Display artifact & Add flows2fim to PATH
      run: |
        ls -R builds/${{ matrix.build_version }}
        chmod a+x ./builds/${{ matrix.build_version }}/flows2fim 
        ./builds/${{ matrix.build_version }}/flows2fim --version
        echo "builds/${{ matrix.build_version }}" >> $GITHUB_PATH

    # - name: Verify flows2fim is available
    #   if: ${{ matrix.os }} == 'ubuntu-latest'
    #   run: |
    #     flows2fim --version

    - name: Install & Configure GDAL
      run: |
        sudo apt-get update && sudo apt-get install -y gdal-bin
        ls /usr/lib/python3/dist-packages/osgeo_utils/samples/
        sudo cp /usr/lib/python3/dist-packages/osgeo_utils/samples/gdal_ls.py /usr/local/bin
        sudo chmod a+x /usr/local/bin/gdal_ls.py
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Verify Installations
      run: |
        flows2fim --version
        gdalinfo --version
        gdal_ls --version

    # - name: Test flows2fim controls
    #   run: flows2fim controls --param1 value1 --param2 value2

    # - name: Test flows2fim fim
    #   run: flows2fim fim --param3 value3 --param4 value4

    # - name: Test flows2fim validate
    #   run: flows2fim validate --param5 value5 --param6 value6

    # - name: Upload test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-results-${{ matrix.os }}
    #     path: test-results/

